config:
    secrets:
        backend_kwargs: '{"connections_prefix": "airflow/connections", "variables_prefix": "airflow/variables", "region_name": "us-east-1"}'
    # webserver:
    #     authenticate: true
    #     auth_backend: airflow.contrib.auth.backends.google_auth
    #     web_server_ssl_cert = <path to cert>
    #     web_server_ssl_key = <path to key>
    #     web_server_port = 443
    #     base_url = http://<hostname or IP>:443
    # celery:
    #     ssl_active = True
    #     ssl_key = <path to key>
    #     ssl_cert = <path to cert>
    #     ssl_cacert = <path to cacert>

service:
  type: LoadBalancer # or another type as needed
  annotations:
    alb.ingress.kubernetes.io/scheme: "internal"
